name: draid
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  flutter_svg_icons: ^0.0.1+4
  flutter_svg: ^2.0.10+1
  #shared_preferences: ^2.2.3
  #shared_preferences_web: ^0.1.2+7
  shared_preferences: ^2.2.3
  shared_preferences_web: ^2.3.0
  dcache: ^0.4.0
  dio: ^5.4.3+1
  path_provider: ^2.1.3
  path: ^1.9.0
  image_picker_web: ^4.0.0
  file_picker: ^8.0.5
  image_picker_for_web: ^3.0.4
  path_drawing: ^1.0.1
  xml: ^6.5.0
  video_player: ^2.9.0
  url_launcher: ^6.3.0
  http: ^1.2.1
  http_parser: ^4.0.2
  js: ^0.6.3
  intl: ^0.17.0
  flutter_colorpicker: ^1.1.0
  flutter_easyloading: ^3.0.5
  jwt_decode: ^0.3.1
  flutter_secure_storage: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg_provider: ^1.0.7
  flutter_svg_click_listener: ^0.0.8
  mime: any
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/logo.svg
    - videos/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
